ARG PHP_VERSION



FROM wordpress:php${PHP_VERSION:-8.0}-fpm-alpine

RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS} \
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && apk del pcre-dev ${PHPIZE_DEPS}
